language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - tip
env:
  - LIBWEBP_VERSION="0.4.1"
  - LIBWEBP_VERSION="0.4.2"
  - LIBWEBP_VERSION="0.4.3"
  - LIBWEBP_VERSION="0.5.0"

cache:
  directories:
    - $HOME/cache
sudo: false

before_install:
  - >
      test -e $HOME/cache/libwebp-${LIBWEBP_VERSION}/lib/libwebp.so || (
      cd /tmp
      && wget http://downloads.webmproject.org/releases/webp/libwebp-${LIBWEBP_VERSION}.tar.gz
      && tar xf libwebp-${LIBWEBP_VERSION}.tar.gz
      && cd libwebp-${LIBWEBP_VERSION}
      && ./configure --prefix=$HOME/cache/libwebp-${LIBWEBP_VERSION}
      && make
      && make install
      )
  - cd $HOME/gopath/src/github.com/harukasan/go-libwebp
  - export CGO_CFLAGS="-I $HOME/cache/libwebp-${LIBWEBP_VERSION}/include"
  - export CGO_LDFLAGS="-L $HOME/cache/libwebp-${LIBWEBP_VERSION}/lib"
  - export LD_LIBRARY_PATH=$HOME/cache/libwebp-${LIBWEBP_VERSION}/lib:$LD_LIBRARY_PATH
