language: go

go:
  - 1.3
  - 1.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjpeg-dev libpng-dev libtiff-dev libgif-dev
  - > 
      cd /tmp
      && wget http://downloads.webmproject.org/releases/webp/libwebp-0.4.2.tar.gz
      && tar xf libwebp-0.4.2.tar.gz
      && cd libwebp-0.4.2
      && ./configure
      && make
      && sudo make install
  - cd $HOME/gopath/src/github.com/harukasan/go-libwebp
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
